name: CI
on:
  push:
    branches:
      - master
      - beta
      - next
jobs:
  release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: node -v && npm -v
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
            semantic_version: 17.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_USERNAME: jgroth
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
