name: CI
on:
  push:
    branches:
      - main
      - beta
      - next
jobs:
  release:
    name: Run Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: node -v && npm -v
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
            semantic_version: 19.0.5
            extra_plugins: |
              @semantic-release/changelog@6.0.2
              @semantic-release/exec@6.0.3
              @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_USERNAME: jgroth
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
